---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-example-app
  labels:
    app.kubernetes.io/name: api-example-app
    app.kubernetes.io/part-of: api-example-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: api-example-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-example-app
        app.kubernetes.io/part-of: api-example-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: api-example-app
          image: api-example-app-image
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 100Mi
              cpu: 200m
            limits:
              memory: 500Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http


