---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-example

resources:
  - deployment.yaml
  - hpa.yaml
  - service.yaml

images:
  - name: api-example-app-image
    newName: bizrad/api-example-app
    newTag: 4a31714f3fa085267c602d2d678869e355a182de