---
apiVersion: v1
kind: Service
metadata:
  name: api-example
  labels:
    app.kubernetes.io/part-of: api-example-app
  annotations:
    prometheus.io/port: http
    prometheus.io/path: /metrics
    prometheus.io/scrape: 'true'
spec:
  selector:
    app.kubernetes.io/name: api-example-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  type: ClusterIP